import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Container, Row, Col } from 'react-bootstrap';
import Discount from '../component/Discount';
import Product from '../component/Product';
import SideBag from '../component/SideBag';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by Rajib" />
      </Head>
      <section className={styles.home_page_section}>
        <Container>
          <Row>
            <Col lg={3}>
              <div className={styles.home_page_product_catagory}>
                <ul>
                  <li>
                    <Link href='/'>vagetable</Link>
                  </li>
                  <li>
                    <Link href='/'>fruit & nut gift</Link>
                  </li>
                  <li>
                    <Link href='/'>organic food</Link>
                  </li>
                  <li>
                    <Link href='/'>fruit drink</Link>
                  </li>
                  <li>
                    <Link href='/'>orange juice</Link>
                  </li>
                  <li>
                    <Link href='/'>oatmeal</Link>
                  </li>
                  <li>
                    <Link href='/'>fresh onion</Link>
                  </li>
                  <li>
                    <Link href='/'>cool drinks</Link>
                  </li>
                  <li>
                    <Link href='/'>soft drink</Link>
                  </li>
                  <li>
                    <Link href='/'>dried food</Link>
                  </li>
                  <li>
                    <Link href='/'>apple juice</Link>
                  </li>
                  <li>
                    <Link href='/'>dried nut</Link>
                  </li>
                </ul>
              </div>
            </Col>
            <Col lg={9}>
              <div className={styles.home_page_silde_part}>
                <p className={styles.home_page_title}>orange</p>
                <h3 className={styles.home_page_heading}>Best Organic Fresh Fruit <br />and Vegetable</h3>
                <span className={styles.home_page_product_price}>
                  <del>$57.00</del>
                  -
                  <ins>$50.00</ins>
                </span>
                <Link href='/'>
                  <a className={styles.home_page_btn_buy_now}>buy now</a>
                </Link>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
      <Discount />
      <Product />
      <SideBag />
    </div >
  )
}
